[package]
name = "gam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.7"
ctrlc = "3.4.1"
macon = "1.0.0"
term_size = "0.3.2"
